describe('movie', () => {
    beforeEach(() => {
        cy.visit('https://the-good-bad-and-last-airbender.vercel.app/')
        cy.intercept('GET', "https://gbla-api.vercel.app/findmovie/wBDLRvjHVOY", {fixture: 'singlemovie'})
    })

    it('should be be able to find and click a movie from the homepage, and initially see a movie title and trailer', () => {
        cy.get('[class*=tertiary_intro_movie_poster]')
        .first()
        .click()
        cy.get('[class*=tertiary_intro_movie_poster]')
        .should('be.visible')
        cy.get('[class*=trailer_title]')
        .should('be.visible')
        cy.get('[class*=movie_trailer]')
        .should('be.visible')
        .should('have.attr', 'src')
        .should('eq', 'https://www.youtube.com/embed/42_UHhpq530')
    })

    it('should be able to click an arrow and navigate down to a section with more details about the movie with a poster', () => {
        cy.get('[class*=tertiary_intro_movie_poster]')
        .first()
        .click()
        cy.get('[class*=link_to_details]')
        .should('be.visible')
        .click()
        cy.get('[class*=movie_poster]')
        .should('be.visible')
        .should('have.attr', 'src')
        .should('eq', "https://m.media-amazon.com/images/I/61zFh8+gdrL.jpg")
        cy.get('[class*=info_box]')
        .should('be.visible')
        cy.get('[class*=title_line]')
        .contains('The Lighthouse')
        .should('be.visible')
        cy.get('[class*=lead_actors]')
        .contains('Lead Actors: Willem Dafoe, Robert Pattinson, and Valeriia Karaman')
        .should('be.visible')
        cy.get('[class*=director]')
        .contains('Director: Robert Eggers')
        .should('be.visible')
        cy.get('[class*=release_year]')
        .contains('Release Year: 2019')
        .should('be.visible')
        cy.get('[class*=runtime]')
        .contains('Runtime: 110 minutes')
        .should('be.visible')
        cy.get('[class*=review]')
        .contains('Easily a top 10 movie that I have ever seen. The black and white emphasizes the dread that overshadows the entire movie and is the perfect touch. The acting from Pattinson and Dafoe is sublime, with Dafoe giving one of the best monologues in cinema history. Watch two men descend into madness as they are overtaken by the solemn embrace of a godforsaken rock.')
        .should('be.visible')
        cy.get('[class*=rating]')
        .contains('Rating: 9.5/10')
        .should('be.visible')
    })
})